### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by WolfMTK** [WolfMTK/speedy#10]
# Initial roadmap

- [ ] Create routing
- [ ] Add the ability to create endpoints
- [ ] Create a basic Middleware and CORS implementation
- [ ] Create an application interface and add router processing
- [ ] Achieve up to 60-80% test coverage
- [ ] Start drafting the second roadmap
